### ISSUE TITLE
No module named helpers

### ISSUE THREAD

**Issue by jjbursik** [AnthonyBloomer/weather-api#17]
Unable to find missing dependency:

```
$ pip install --user weather-api
Collecting weather-api
  Using cached https://files.pythonhosted.org/packages/04/8f/87185f20f56ae9caa0ead9cf3a17dd5b94005c91832ce2003654f26a320b/weather_api-1.0.5-py2.py3-none-any.whl
Requirement already satisfied: requests in ./.local/lib/python2.7/site-packages (from weather-api) (2.19.1)
Requirement already satisfied: idna<2.8,>=2.5 in ./.local/lib/python2.7/site-packages (from requests->weather-api) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python2.7/site-packages (from requests->weather-api) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./.local/lib/python2.7/site-packages (from requests->weather-api) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python2.7/site-packages (from requests->weather-api) (2018.8.24)
Installing collected packages: weather-api
Successfully installed weather-api-1.0.5

$ weather dublin --u c
Traceback (most recent call last):
  File "/home/.local/bin/weather", line 7, in <module>
    from weather.main import main
  File "/home/.local/lib/python2.7/site-packages/weather/__init__.py", line 1, in <module>
    from .weather import Weather
  File "/home/.local/lib/python2.7/site-packages/weather/weather.py", line 3, in <module>
    from .objects.weather_obj import WeatherObject
  File "/home/.local/lib/python2.7/site-packages/weather/objects/weather_obj.py", line 1, in <module>
    from .forecast_obj import Forecast
  File "/home/.local/lib/python2.7/site-packages/weather/objects/forecast_obj.py", line 1, in <module>
    from weather.helpers import add_leading_zero
ImportError: No module named helpers
```

**Comment by AnthonyBloomer** [comment]
Fixed with https://github.com/AnthonyBloomer/weather-api/commit/7a7c544060ef7a76871f70226e6a42cb11f1b9e3
